#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
constants.py — named mathematical constant digit generator

Generates digit strings for named constants suitable for use as
initialisation vectors in the Channel Camouflage Layer and Mnemonic
Share Wrapping constructions.

Generated files conform to the Crowsong Archivist Header Format (CAHF)
as specified in draft-darley-crowsong-archivist-00.  Any CAHF-conformant
tool (archivist.py, texts.py, udhr.py, etc.) can verify the output of
this tool, and this tool can verify any CAHF-stamped file that carries
CONSTANT and DIGITS fields.

Usage:
    python constants.py list
    python constants.py digits <name> <count>
    python constants.py show <name> <count>
    python constants.py generate <name> <count> <outfile>
    python constants.py verify <name> <infile>

Examples:
    python constants.py list
    python constants.py digits pi 100
    python constants.py show phi 200
    python constants.py generate sqrt2 10000 docs/constants/sqrt2-10000.txt
    python constants.py verify pi docs/constants/pi-10000.txt

Requires:
    mpmath  (pip install mpmath)

Generated files are plain UTF-8 text and require no dependencies to read.

CAHF conformance: draft-darley-crowsong-archivist-00, sections 2-6, 8.
SHA256 and CRC32 are computed over the normalised formatted body (spaces
and line-breaks included), not over the raw digit string.  Both fields
are mandatory: files generated by older tools that lack CRC32 must be
re-generated before they will pass verification.

Named constants are public deterministic reference material.  They are
suitable as declared IV anchors but provide no secrecy, unpredictability,
or cryptographic strength.

Compatibility: Python 2.7+ / 3.x
Author: Proper Tools SRL
License: MIT
"""

from __future__ import print_function, unicode_literals

import argparse
import hashlib
import io
import os
import sys
import time
import zlib

try:
    import mpmath
    MPMATH_AVAILABLE = True
except ImportError:
    MPMATH_AVAILABLE = False


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GROUP_SIZE     = 10
GROUPS_PER_LINE = 6
EXTRA_PRECISION = 40

TOOL_PATH = "tools/constants.py"

# CAHF sentinel and marker (draft-darley-crowsong-archivist-00 §2.2, §2.3)
CAHF_MARKER   = "# ARCHIVIST  v1.0"
CAHF_SENTINEL = "# ---END-HEADER---"


# ---------------------------------------------------------------------------
# Python 2/3 compatibility
# ---------------------------------------------------------------------------

# Cached UTF-8 wrappers around stdout/stderr.  Initialised on first use.
# Falls back to the raw sys stream if fileno() is unavailable (e.g. in
# captured test environments).
_STDOUT = None
_STDERR = None


def _get_stdout():
    global _STDOUT
    if _STDOUT is None:
        try:
            _STDOUT = io.open(sys.stdout.fileno(), "w", encoding="utf-8", closefd=False)
        except Exception:
            _STDOUT = sys.stdout
    return _STDOUT


def _get_stderr():
    global _STDERR
    if _STDERR is None:
        try:
            _STDERR = io.open(sys.stderr.fileno(), "w", encoding="utf-8", closefd=False)
        except Exception:
            _STDERR = sys.stderr
    return _STDERR


def out(text=""):
    """Write a line to stdout as UTF-8."""
    _get_stdout().write(text + "\n")


def err(text=""):
    """Write a line to stderr as UTF-8."""
    _get_stderr().write(text + "\n")


# ---------------------------------------------------------------------------
# Constant registry
# ---------------------------------------------------------------------------

def _pi(mp):    return mp.pi
def _e(mp):     return mp.e
def _phi(mp):   return mp.phi
def _sqrt2(mp): return mp.sqrt(2)
def _sqrt3(mp): return mp.sqrt(3)
def _sqrt5(mp): return mp.sqrt(5)
def _ln2(mp):   return mp.log(2)
def _apery(mp): return mp.apery


CONSTANTS = {
    "pi": {
        "fn":     _pi,
        "name":   "Pi",
        "symbol": "π",
        "oeis":   "A000796",
        "notes":  "Ratio of circumference to diameter. Infinite, non-repeating.",
    },
    "e": {
        "fn":     _e,
        "name":   "Euler's number",
        "symbol": "e",
        "oeis":   "A001113",
        "notes":  "Base of the natural logarithm. Infinite, non-repeating.",
    },
    "phi": {
        "fn":     _phi,
        "name":   "Golden ratio",
        "symbol": "φ",
        "oeis":   "A001622",
        "notes":  "Limit of consecutive Fibonacci ratios. Infinite, non-repeating.",
    },
    "sqrt2": {
        "fn":     _sqrt2,
        "name":   "Square root of 2",
        "symbol": "√2",
        "oeis":   "A002193",
        "notes":  "First known irrational number. Infinite, non-repeating.",
    },
    "sqrt3": {
        "fn":     _sqrt3,
        "name":   "Square root of 3",
        "symbol": "√3",
        "oeis":   "A002194",
        "notes":  "Infinite, non-repeating.",
    },
    "sqrt5": {
        "fn":     _sqrt5,
        "name":   "Square root of 5",
        "symbol": "√5",
        "oeis":   "A002163",
        "notes":  "Infinite, non-repeating.",
    },
    "ln2": {
        "fn":     _ln2,
        "name":   "Natural logarithm of 2",
        "symbol": "ln(2)",
        "oeis":   "A002162",
        "notes":  "Infinite, non-repeating.",
    },
    "apery": {
        "fn":     _apery,
        "name":   "Apery's constant",
        "symbol": "ζ(3)",
        "oeis":   "A002117",
        "notes":  "Sum of reciprocals of cubes. Infinite, likely non-repeating.",
    },
}


# ---------------------------------------------------------------------------
# argparse helpers
# ---------------------------------------------------------------------------

def positive_int(value):
    """argparse type: integer >= 1."""
    try:
        ivalue = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be an integer >= 1")
    if ivalue < 1:
        raise argparse.ArgumentTypeError("must be >= 1")
    return ivalue


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def require_mpmath():
    """Fail clearly if mpmath is unavailable."""
    if not MPMATH_AVAILABLE:
        raise RuntimeError(
            "mpmath is required for digit generation.\n"
            "Install with: pip install mpmath"
        )


def get_constant_meta(name):
    """Return (key, meta) for a constant name, or raise ValueError."""
    key = name.lower()
    if key not in CONSTANTS:
        raise ValueError("unknown constant: {0}".format(name))
    return key, CONSTANTS[key]


def get_digits(name, count):
    """
    Return the first `count` decimal digits of the named constant as a plain
    digit string (no decimal point, no whitespace).

    Digits begin with the leading integer digit, e.g. pi -> '31415...'.
    mpmath global precision is saved and restored.
    """
    require_mpmath()
    key, meta = get_constant_meta(name)

    old_dps = mpmath.mp.dps
    try:
        mpmath.mp.dps = count + EXTRA_PRECISION
        value = meta["fn"](mpmath.mp)
        rendered = mpmath.nstr(value, count + 20, strip_zeros=False)
        digits = "".join(ch for ch in rendered if ch.isdigit())
    finally:
        mpmath.mp.dps = old_dps

    if len(digits) < count:
        raise RuntimeError(
            "insufficient digits generated for {0}: wanted {1}, got {2}".format(
                key, count, len(digits)
            )
        )

    return digits[:count]


def format_digits(digits, group=GROUP_SIZE, per_line=GROUPS_PER_LINE):
    """
    Format a digit string into grouped, line-wrapped output.

    Default: 10 digits per group, 6 groups per line (60 digits per line).
    """
    groups = [digits[i:i + group] for i in range(0, len(digits), group)]
    lines = [
        " ".join(groups[i:i + per_line])
        for i in range(0, len(groups), per_line)
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hashing and integrity (CAHF §4)
# ---------------------------------------------------------------------------

def _normalise_line_endings(text):
    """
    Normalise line endings to LF per CAHF §4.1.
    CRLF must be replaced before bare CR to avoid double-replacement.
    """
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")
    return text


def _normalise_body(body):
    """
    Normalise line endings and strip trailing newlines per CAHF §4.1-4.2.
    This produces the string that is hashed during stamping and verification.
    """
    return _normalise_line_endings(body).rstrip("\n")


def sha256_hex(text):
    """
    Return SHA-256 of a Unicode string encoded as UTF-8.
    Input must already be normalised per CAHF §4.3.
    """
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def crc32_hex(text):
    """
    Return CRC32 of a Unicode string encoded as UTF-8, as an 8-character
    lowercase hex string.  Provides a quick manual/transcription error check.
    """
    data = text.encode("utf-8")
    return "{0:08x}".format(zlib.crc32(data) & 0xffffffff)


# ---------------------------------------------------------------------------
# CAHF file generation (draft-darley-crowsong-archivist-00 §5)
# ---------------------------------------------------------------------------

def make_cahf_file(name, count, digits):
    """
    Build and return a complete CAHF-stamped constant digit file as a
    Unicode string, ready to write to disk.

    SHA256 and CRC32 are computed over the normalised formatted body
    (i.e. the digit string with spaces and newlines), NOT over the raw
    digit string.  This ensures that any CAHF-conformant verifier can
    recompute the digest by extracting the body after the sentinel and
    applying the standard CAHF hashing contract (§4.4).

    File structure (per CAHF §5):
        <header block>
        # ---END-HEADER---
        <body>
        <one trailing LF>
    """
    _, meta = get_constant_meta(name)
    date = time.strftime("%Y-%m-%d")

    # The body is the formatted digit string.
    # Normalise it before hashing per CAHF §4.4(a).
    body_raw = format_digits(digits)
    body_for_hash = _normalise_body(body_raw)
    digest = sha256_hex(body_for_hash)
    crc    = crc32_hex(body_for_hash)

    header_lines = [
        CAHF_MARKER,
        "#",
        "# TITLE      {0} — {1}".format(meta["symbol"], meta["name"]),
        "# CONSTANT   {0}".format(name),
        "# OEIS       {0}".format(meta["oeis"]),
        "# NOTE       {0}".format(meta["notes"]),
        "#",
        "# DIGITS     {0}".format(count),
        "# FORMAT     decimal, {0} digits per group, {1} groups per line".format(
            GROUP_SIZE, GROUPS_PER_LINE
        ),
        "#",
        "# NOTE       Named constants are public deterministic reference material.",
        "# NOTE       They provide no secrecy, unpredictability, or cryptographic",
        "# NOTE       strength.  Suitable as declared IV anchors only.",
        "#",
        "# DATE       {0}".format(date),
        "# TOOL       {0} (Proper Tools SRL)".format(TOOL_PATH),
        "#",
        "# CRC32      {0}".format(crc),
        "# SHA256     {0}".format(digest),
    ]

    header_block = "\n".join(header_lines)

    # CAHF §5 step 5: header + sentinel + body + one trailing LF.
    # No blank line between sentinel and body (§2.3).
    return (
        header_block + "\n" +
        CAHF_SENTINEL + "\n" +
        body_for_hash + "\n"
    )


# ---------------------------------------------------------------------------
# CAHF file parsing (draft-darley-crowsong-archivist-00 §6)
# ---------------------------------------------------------------------------

def parse_cahf_file(path):
    """
    Parse a CAHF-stamped constant digit file.

    Implements the verification parsing procedure from CAHF §6, including:
      - ARCHIVIST marker gate (§6.1 step 3)
      - Sentinel detection (§6.1 step 4)
      - Body extraction and normalisation (§6.2, §4.4(c))
      - Strict body character validation

    Returns a dict with keys:
        fields          -- dict of all parsed header fields (uppercase keys)
        body_for_hash   -- normalised body string (what to hash)
        digits          -- digit characters extracted from body
        sha256_declared -- value of SHA256 header field, or None
        name_declared   -- value of CONSTANT header field, or None
        count_declared  -- value of DIGITS header field as int, or None
        crc32_declared  -- value of CRC32 header field, or None

    Raises ValueError with a descriptive message for any structural problem.
    """
    with io.open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Normalise line endings per CAHF §4.1
    content = _normalise_line_endings(content)
    lines = content.split("\n")

    # Gate on ARCHIVIST marker per CAHF §6.1 step 3.
    # Require exact match against CAHF_MARKER so version mismatches are caught
    # explicitly rather than silently accepted.
    first_nonempty = next((l for l in lines if l.strip()), "")
    if first_nonempty != CAHF_MARKER:
        raise ValueError(
            "not a CAHF file or unsupported version: "
            "expected {0!r} as first non-empty line, got {1!r}.\n"
            "Re-generate this file with a CAHF-conformant tool.".format(
                CAHF_MARKER, first_nonempty
            )
        )

    # Locate sentinel per CAHF §6.1 step 4
    if CAHF_SENTINEL not in lines:
        raise ValueError(
            "legacy or malformed CAHF file: sentinel '{0}' not found.\n"
            "Re-stamp this file with a CAHF-conformant tool.".format(CAHF_SENTINEL)
        )

    sentinel_idx = lines.index(CAHF_SENTINEL)
    header_lines = lines[:sentinel_idx]
    body_lines   = lines[sentinel_idx + 1:]

    # Parse header fields per CAHF §2.2
    # Accept both canonical double-space and legacy colon separator (§7.3),
    # but only for the known CAHF field names.
    #
    # Singleton fields must appear at most once; duplicates in integrity-critical
    # fields (SHA256, CRC32, CONSTANT, DIGITS) indicate a malformed or tampered
    # header and are rejected immediately.  Repeatable fields (NOTE) accumulate
    # as lists.  Unknown fields are stored as singletons (last-write-wins).
    SINGLETON_FIELDS = {
        "ARCHIVIST", "SHA256", "CRC32", "TITLE", "AUTHOR", "LANG",
        "SOURCE", "DATE", "FETCHED", "ENTRIES", "CHARS", "LINES",
        "TAGS", "TLP", "LICENSE", "TOOL",
        # Tool-specific extensions
        "CONSTANT", "OEIS", "DIGITS", "FORMAT",
    }
    REPEATABLE_FIELDS = {"NOTE"}
    # Combined set for the field-recognition gate
    KNOWN_FIELDS = SINGLETON_FIELDS | REPEATABLE_FIELDS

    fields = {}

    def _store_field(fname, fval):
        """Store a parsed header field.

        Singleton fields raise ValueError on duplication.
        Repeatable fields (NOTE) accumulate as lists.
        Unknown fields are stored as singletons by default.
        """
        if fname in SINGLETON_FIELDS:
            if fname in fields:
                raise ValueError(
                    "duplicate singleton header field: {0!r} — "
                    "file is malformed or tampered.".format(fname)
                )
            fields[fname] = fval
            return
        if fname in REPEATABLE_FIELDS:
            if fname in fields:
                existing = fields[fname]
                if isinstance(existing, list):
                    existing.append(fval)
                else:
                    fields[fname] = [existing, fval]
            else:
                fields[fname] = fval
            return
        # Unknown field — store as singleton (last-write-wins is fine for unknowns)
        fields[fname] = fval

    for line in header_lines:
        if not line.startswith("# "):
            continue
        rest = line[2:]
        if not rest or rest == "#":
            continue

        # Try canonical whitespace-separated format first (§2.2).
        # We accept any run of whitespace as separator for robustness across
        # tools, and document this as the verified-acceptable form.
        parts = rest.split(None, 1)
        if len(parts) == 2 and parts[0].upper() in KNOWN_FIELDS:
            _store_field(parts[0].upper(), parts[1].strip())
        elif len(parts) == 1 and parts[0].upper().rstrip(":") in KNOWN_FIELDS:
            # bare field name with no value
            _store_field(parts[0].upper().rstrip(":"), "")
        else:
            # Try legacy colon separator (§7.3), restricted to known fields
            if ":" in rest:
                fname, _, fval = rest.partition(":")
                fname = fname.strip().upper()
                if fname in KNOWN_FIELDS:
                    _store_field(fname, fval.strip())

    # Extract and validate the body per CAHF §6.2 and §4.4(c).
    # Use _normalise_body() for exact symmetry with the stamping path.
    body_text = "\n".join(body_lines)
    body_for_hash = _normalise_body(body_text)

    # Strict body character validation: only digits and whitespace permitted.
    # Any other character indicates tampering or format corruption.
    for lineno, bline in enumerate(body_for_hash.split("\n"), 1):
        for ch in bline:
            if not (ch.isdigit() or ch in " \t"):
                raise ValueError(
                    "invalid character {0!r} in digit body at line {1}.\n"
                    "Expected only decimal digits and whitespace.".format(ch, lineno)
                )

    digits = "".join(ch for ch in body_for_hash if ch.isdigit())

    # Parse typed fields
    sha256_declared = fields.get("SHA256")
    crc32_declared  = fields.get("CRC32")
    name_declared   = fields.get("CONSTANT")

    count_declared = None
    if "DIGITS" in fields:
        try:
            count_declared = int(fields["DIGITS"])
        except ValueError:
            raise ValueError(
                "malformed DIGITS field: {0!r}".format(fields["DIGITS"])
            )

    return {
        "fields":          fields,
        "body_for_hash":   body_for_hash,
        "digits":          digits,
        "sha256_declared": sha256_declared,
        "crc32_declared":  crc32_declared,
        "name_declared":   name_declared,
        "count_declared":  count_declared,
    }


# ---------------------------------------------------------------------------
# Subcommand implementations
# ---------------------------------------------------------------------------

def cmd_list(_args):
    """List all known constants."""
    fmt = "{:<8}  {:<6}  {:<10}  {}"
    out(fmt.format("name", "symbol", "OEIS", "notes"))
    out("-" * 72)
    for key in sorted(CONSTANTS):
        meta = CONSTANTS[key]
        out(fmt.format(
            key,
            meta["symbol"],
            meta["oeis"],
            meta["notes"][:50]
        ))
    return 0


def cmd_digits(args):
    """Print plain digits only — pipeable."""
    out(get_digits(args.name, args.count))
    return 0


def cmd_show(args):
    """Print formatted digits with heading."""
    key, meta = get_constant_meta(args.name)
    digits = get_digits(key, args.count)
    out("{symbol} — {name} ({count} digits)".format(
        symbol=meta["symbol"],
        name=meta["name"],
        count=args.count
    ))
    out()
    out(format_digits(digits))
    return 0


def cmd_generate(args):
    """Generate a CAHF-stamped constant digit file."""
    key, _meta = get_constant_meta(args.name)
    digits = get_digits(key, args.count)
    file_content = make_cahf_file(key, args.count, digits)

    outdir = os.path.dirname(args.outfile)
    if outdir:
        try:
            os.makedirs(outdir)
        except OSError:
            if not os.path.isdir(outdir):
                raise

    with io.open(args.outfile, "w", encoding="utf-8") as f:
        f.write(file_content)

    # Recompute for display — body_for_hash is format_digits(digits).rstrip("\n")
    body_for_hash = _normalise_body(format_digits(digits))
    out("Written:  {0}".format(args.outfile))
    out("Digits:   {0}".format(args.count))
    out("CRC32:    {0}".format(crc32_hex(body_for_hash)))
    out("SHA256:   {0}".format(sha256_hex(body_for_hash)))
    return 0


def cmd_verify(args):
    """
    Verify a CAHF-stamped constant digit file.

    Checks:
      1. CAHF structural validity (ARCHIVIST marker, sentinel)
      2. All required metadata fields present (CONSTANT, DIGITS, CRC32, SHA256)
      3. Declared CONSTANT matches the name given on the CLI
      4. Declared DIGITS matches the digit count found in the body
      5. CRC32 of body matches declared CRC32
      6. SHA256 of body matches declared SHA256
      7. Digits recomputed from first principles match the file body

    Any single failure causes overall FAIL and exit code 1.
    CRC32 is mandatory: files lacking it must be re-generated.
    """
    key, _meta = get_constant_meta(args.name)

    parsed = parse_cahf_file(args.infile)

    digits        = parsed["digits"]
    body_for_hash = parsed["body_for_hash"]

    if not digits:
        err("Error: no digits found in file body.")
        return 1

    # --- Require all mandatory fields ---
    # CRC32 is mandatory: this tool always emits it, so its absence means
    # the file was not generated by a conformant tool and should be re-generated.
    missing = []
    if parsed["name_declared"] is None:
        missing.append("CONSTANT")
    if parsed["count_declared"] is None:
        missing.append("DIGITS")
    if parsed["sha256_declared"] is None:
        missing.append("SHA256")
    if parsed["crc32_declared"] is None:
        missing.append("CRC32")
    if missing:
        err("Error: missing required header fields: {0}".format(", ".join(missing)))
        err("Re-generate this file with: python constants.py generate <name> <count> <outfile>")
        err("Verification: FAIL")
        return 1

    # --- Run all checks ---
    count = len(digits)

    name_ok  = (parsed["name_declared"].lower() == key)
    count_ok = (parsed["count_declared"] == count)

    sha256_actual = sha256_hex(body_for_hash)
    sha256_ok     = (sha256_actual == parsed["sha256_declared"].lower())

    crc32_actual  = crc32_hex(body_for_hash)
    crc32_ok      = (crc32_actual == parsed["crc32_declared"].lower())

    recomputed = get_digits(key, count)
    digits_ok  = (digits == recomputed)

    # --- Report ---
    def status(ok, extra=""):
        return "OK" if ok else "FAIL" + (" ({0})".format(extra) if extra else "")

    out("File:         {0}".format(args.infile))
    out("Constant:     {0} — {1}".format(
        key,
        status(name_ok, "declared: {0}".format(parsed["name_declared"]))
    ))
    out("Digits:       {0} — {1}".format(
        count,
        status(count_ok, "declared: {0}".format(parsed["count_declared"]))
    ))
    out("CRC32:        {0} — {1}".format(
        crc32_actual,
        status(crc32_ok, "declared: {0}".format(parsed["crc32_declared"]))
    ))
    out("SHA256:       {0} — {1}".format(
        sha256_actual,
        status(sha256_ok, "declared: {0}".format(parsed["sha256_declared"]))
    ))
    out("Recomputed:   {0}".format(
        "OK — digits match" if digits_ok else "FAIL — digits differ"
    ))

    all_ok = name_ok and count_ok and sha256_ok and crc32_ok and digits_ok
    out("Verification: {0}".format("PASS" if all_ok else "FAIL"))
    return 0 if all_ok else 1


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Named mathematical constant digit generator.\n"
            "Produces CAHF-stamped digit files for IV sources and related\n"
            "constructions.  See draft-darley-crowsong-archivist-00."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python constants.py list\n"
            "  python constants.py digits pi 100\n"
            "  python constants.py show phi 200\n"
            "  python constants.py generate e 10000 docs/constants/e-10000.txt\n"
            "  python constants.py verify pi docs/constants/pi-10000.txt\n"
            "\n"
            "Canonical test vector:\n"
            "  name:   pi\n"
            "  count:  32\n"
            "  digits: 31415926535897932384626433832795\n"
        )
    )

    subparsers = parser.add_subparsers(dest="command")

    p_list = subparsers.add_parser("list", help="list all known constants")
    p_list.set_defaults(func=cmd_list)

    p_digits = subparsers.add_parser(
        "digits",
        help="print the first N digits of a constant (plain, pipeable)"
    )
    p_digits.add_argument("name", help="constant name (see list)")
    p_digits.add_argument("count", type=positive_int, help="number of digits")
    p_digits.set_defaults(func=cmd_digits)

    p_show = subparsers.add_parser(
        "show",
        help="print the first N digits, formatted for readability"
    )
    p_show.add_argument("name", help="constant name (see list)")
    p_show.add_argument("count", type=positive_int, help="number of digits")
    p_show.set_defaults(func=cmd_show)

    p_generate = subparsers.add_parser(
        "generate",
        help="generate a CAHF-stamped digit file"
    )
    p_generate.add_argument("name", help="constant name (see list)")
    p_generate.add_argument("count", type=positive_int, help="number of digits")
    p_generate.add_argument("outfile", help="output file path")
    p_generate.set_defaults(func=cmd_generate)

    p_verify = subparsers.add_parser(
        "verify",
        help="verify a CAHF-stamped digit file against its declared metadata"
    )
    p_verify.add_argument("name", help="constant name (for recomputation)")
    p_verify.add_argument("infile", help="file to verify")
    p_verify.set_defaults(func=cmd_verify)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    # Python 2.7-safe subcommand enforcement: subparsers.required is not
    # reliable on Py2, so we check manually here.
    if not getattr(args, "command", None):
        parser.print_help(file=sys.stderr)
        return 1

    try:
        return args.func(args)
    except (ValueError, RuntimeError, IOError) as exc:
        err("Error: {0}".format(exc))
        return 1


if __name__ == "__main__":
    sys.exit(main())
